#!/bin/bash

wget -O - $1 2>/dev/null | html2text -o - | tail --lines=+12 | head --lines=-3 | sed -e "s/^Indicators/**** Indicators/" | sed -e "s/^Subfield Codes/**** Subfield Codes/" | sed -e "s/^Examples/**** Examples/" | sed -e "s/^\\$\(.*\)-/  + $\1::/" | sed -e "s/^First/***** First/" | sed -e "s/^Second/***** Second/"